### ISSUE TITLE
mvn install didn't install jar files

### ISSUE THREAD

**Issue by haesleinhuepf** [mcib3d/tapas-core#1]
Hi Thomas @mcib3d,

I just tried to build tapas-core locally and realised that maven does only install the pom file to the local repository - not the jar file. In order to make it install the jar file as well, I had to remove this line:

https://github.com/mcib3d/tapas-core/blob/master/pom.xml#L9

If it's becoming more than just this one line, I'll send a pull-request. But it looks good so far! I'm just writing that here before I forget it ;-)

Cheers,
Robert

**Comment by mcib3d** [comment]
Hi Robert,

Yes the pb is fixed in the new release 0.6.2, needed to change to <packaging>jar</packaging>

Thanks

Thomas

**Comment by haesleinhuepf** [comment]
Hey Thomas,

just one more question: The current code on the master branch is still 0.6.1:
https://github.com/mcib3d/tapas-core/blob/master/pom.xml#L10

And my maven can't find the 0.6.2 online
![image](https://user-images.githubusercontent.com/12660498/82541038-22196500-9b50-11ea-8b3c-3c04a11a14b4.png)

Are you sure the deployment to jitpack.io worked? I've never used this online repository, that's why I'm not sure how it works....

Thanks again for your support!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Oh, and there is one more issue: jitpack.io lists the jar like this:
![image](https://user-images.githubusercontent.com/12660498/82541603-05316180-9b51-11ea-8b35-b525503e9695.png)

But in the pom.xml, the gourp-id is different. Likely that's why my maven can't find it:
https://github.com/mcib3d/tapas-core/blob/master/pom.xml#L7
